### ISSUE TITLE
Not Usable on windows (ext-pcntl is not available on  windows platform)

### ISSUE THREAD

**Issue by uwascan** [aarondfrancis/solo#13]
composer require aaronfrancis/solo --dev                                                            
Cannot use aaronfrancis/solo's latest version v0.1.2 as it requires ext-pcntl * which is missing from your platform.

In PackageDiscoveryTrait.php line 325:
                                                                                                                       
  Package aaronfrancis/solo has requirements incompatible with your PHP version, PHP extensions and Composer version   
  :                                                                                                                    
    - aaronfrancis/solo v0.1.2 requires ext-pcntl * but it is not present.                                             
                                                                                                                       

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by jiordiviera** [comment]
Yes, laravel pail is also not compatible on UNIX environments, and therefore Windows operating systems, due to the pcntl extension.

**Comment by atiqsamtia** [comment]
Even if we install with ignoring platform dependencies, it returns this error when trying to run

![image](https://github.com/user-attachments/assets/f2dccd31-fe59-4379-9734-d353c51f88a1)

**Comment by Lem-92** [comment]
Yes, Windows users we are lag behind.

**Comment by simonhamp** [comment]
It's very likely that `pcntl` will [never be supported on Windows](https://externals.io/message/101651#101654). So you'd have to be using it inside of WSL, a Linux Docker container, or some other virtualisation

**Comment by aarondfrancis** [comment]
Hmmm maybe I need to note that this is not usable on Windows. Because yes, it require pctnl. Sorry about that!
