### ISSUE TITLE
Dependencies could not be resolved

### ISSUE THREAD

**Issue by slakbal** [aarondfrancis/solo#18]
Dependency producing error on Mac with Laravel 11:

````
"require": {
        "php": "^8.2",
        "illuminate/support": "^10|^11",
        "illuminate/console": "^10|^11",
        "illuminate/process": "^10|^11",
        "ext-pcntl": "*",
        "joetannenbaum/chewie": "^0.1.8"
    },
````

Error:

````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aaronfrancis/solo[v0.1.1, ..., v0.1.2] require joetannenbaum/chewie ^0.1.8 -> satisfiable by joetannenbaum/chewie[0.1.8].
    - aaronfrancis/solo v0.1.0 requires joetannenbaum/chewie ^0.1.7 -> satisfiable by joetannenbaum/chewie[0.1.7, 0.1.8].
    - joetannenbaum/chewie 0.1.7 requires laravel/prompts ^0.1.15 -> found laravel/prompts[v0.1.15, ..., v0.1.25] but the package is fixed to v0.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - joetannenbaum/chewie 0.1.8 requires laravel/prompts 0.1.x -> found laravel/prompts[v0.1.0, ..., v0.1.25] but the package is fixed to v0.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires aaronfrancis/solo * -> satisfiable by aaronfrancis/solo[v0.1.0, v0.1.1, v0.1.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require aaronfrancis/solo:*" to figure out if any version is installable, or "composer require aaronfrancis/solo:^2.1" if you know which you need.
````

**Comment by slakbal** [comment]
Hey @danmatthews thanks for the feedback. "laravel/prompts" is definitely not in my composer.json dependencies. It's actually a clean project currently where I am getting the error.

**Comment by danmatthews** [comment]
Interesting, this part of the error: `but the package is fixed to v0.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.` led me to believe that.

I would:

- Delete your composer.lock file.
- Re-run `composer install`
- Re-run `composer require aaronfrancis/solo --dev`

See where that gets you.

**Comment by Nielson** [comment]
> Interesting, this part of the error: `but the package is fixed to v0.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.` led me to believe that.
> 
> I would:
> 
> * Delete your composer.lock file.
> * Re-run `composer install`
> * Re-run `composer require aaronfrancis/solo --dev`
> 
> See where that gets you.

I have the same problem and did exactly this - didn't help unfortunately. I didn't have Laravel Prompts installed either.

I get the same error after doing the above instructions:

```
composer require aaronfrancis/solo --dev
./composer.json has been updated
Running composer update aaronfrancis/solo
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aaronfrancis/solo[v0.1.1, ..., v0.1.2] require joetannenbaum/chewie ^0.1.8 -> satisfiable by joetannenbaum/chewie[0.1.8].
    - aaronfrancis/solo v0.1.0 requires joetannenbaum/chewie ^0.1.7 -> satisfiable by joetannenbaum/chewie[0.1.7, 0.1.8].
    - joetannenbaum/chewie 0.1.7 requires laravel/prompts ^0.1.15 -> found laravel/prompts[v0.1.15, ..., v0.1.25] but it conflicts with your root composer.json require (^0.3.1).
    - joetannenbaum/chewie 0.1.8 requires laravel/prompts 0.1.x -> found laravel/prompts[v0.1.0, ..., v0.1.25] but it conflicts with your root composer.json require (^0.3.1).
    - Root composer.json requires aaronfrancis/solo * -> satisfiable by aaronfrancis/solo[v0.1.0, v0.1.1, v0.1.2].
    - ```

**Comment by danmatthews** [comment]
I think potentially this is to do with Chewie having a `composer.lock` file in it's repo.

I'll submit a PR to remove it.

**Comment by IronSinew** [comment]
I believe it is more related to the fact that Chewie's `0.1.8` release wasn't quite as open as Joe thought it would be, but `0.1.9` is, and I've submitted a PR to bump that dep up.

https://github.com/aarondfrancis/solo/pull/21

**Comment by slakbal** [comment]
> I think potentially this is to do with Chewie having a `composer.lock` file in it's repo.
> 
> I'll submit a PR to remove it.

Thanks @danmatthews - Looks like it is working now nicely with the composer.lock removed. 

Ps. nice little trick to version alias a dependency that I wasn't aware off. Used it to temporarily solve the problem:

"joetannenbaum/chewie": "dev-main as 0.1.8",

But with it fixed now, ofcourse not needed anymore.

**Comment by fefo-p** [comment]
Using composer require aaronfrancis/solo --dev -W works fine

**Comment by Nielson** [comment]
> composer require aaronfrancis/solo --dev

I tried that, but it didn't work for me, unfortunately. If you just tried it, it could be because this issue has been fixed now. 

Running composer require aaronfrancis/solo --dev works for me now, at least. Thanks @danmatthews ! :)

**Comment by tnorthcutt** [comment]
@slakbal Sounds like this issue can be closed now - yeah?

**Comment by slakbal** [comment]
100% will close it
