### ISSUE TITLE
not kill `npm run dev` after press q for quit

### ISSUE THREAD

**Issue by ajikamaludin** [aarondfrancis/solo#20]
Hey Aaron, solo is great.

just realized that after several time quit and back run the `solo` command vite always create new port its mean the npm command before its still alive, is this a bug ?

![image](https://github.com/user-attachments/assets/cd72bbc0-7071-494c-9cd3-7ba766610fa4)

**Comment by mrmurb** [comment]
Im facing the same issue with commands like `php artisan serve`. Looks to be the same issue that #10 addressed, but it seems like the fix is not solving the issue.

**Comment by ajikamaludin** [comment]
Detail information : 
- OS  : Debian GNU/Linux 12 (bookworm)
- Node : v22.11.0
- NPM : 10.9.0
- Vite : v5.4.11
- Laravel : v11.30.0

![Peek 2024-11-13 14-53](https://github.com/user-attachments/assets/a3e1bc31-67d1-49af-9980-fe2b06ad0359)

maybe this gif can be hint for the bug , 
running it with normal `npm run dev` from the terminal is just fine, with solo the process is not stopped correctly
i need to kill it manually so it will start with correct port

**Comment by aarondfrancis** [comment]
Ok I think I might've fixed it here: https://github.com/aarondfrancis/solo/commit/2b0b3ea614fda54e51f15d5f43885ef6cb3ec461. 

Let me cut a new release and then y'all let me know!

**Comment by ajikamaludin** [comment]
im trying install `dev-main` version with this fix, but actually it still same 

![image](https://github.com/user-attachments/assets/fa75e83c-802e-4d68-8bec-328614a86354)

**Comment by aarondfrancis** [comment]
I might need to pair with you because I'm not sure hour to reproduce it!
Would you be up for that?

**Comment by aarondfrancis** [comment]
@ajikamaludin can you try dev-main again? I added a monitor process

**Comment by aarondfrancis** [comment]
Fixed! Please reopen if you find another one. Thanks for the help!

**Comment by wrtisans** [comment]
i've the same problem but with reverb, after i quit SOLO and try to restart it, it cant start because the port is in use

**Comment by aarondfrancis** [comment]
@wrtisans can you open another issue? And can you confirm you're on 0.2.1?

**Comment by wrtisans** [comment]
it was my mistake, i was on other older version, i've upgraded and all works fine now, thanks a lot!
