### ISSUE TITLE
Make output colors "pass through"

### ISSUE THREAD

**Issue by morganmsrn** [aarondfrancis/solo#22]
It seems only the Vite output log colors are respected out of the box (images for reference). Is it possible to reproduce that behaviour for other commands ? I'd particularly love to see Pail colors reflected.

---

> Here is the output from Vite in Solo without any extra config change
<img width="559" alt="screenshot 2024-11-13 at 01 39 34" src="https://github.com/user-attachments/assets/c34d2c04-ba68-4b95-8df1-d58bc6dda292">

---

> Here is a comparison from calling Pail from the console directly (colors and boxes) and in Solo (no extra config either, colors are not respected, the box also happens to be truncated)
<img width="873" alt="screenshot 2024-11-13 at 01 39 26" src="https://github.com/user-attachments/assets/333dd1b4-88f4-4136-96de-3ca0a8d7080e">
<img width="1327" alt="screenshot 2024-11-13 at 01 39 42" src="https://github.com/user-attachments/assets/e93bee60-bc3b-483c-8891-8ab76f3f0c77">

**Comment by AlexJump24** [comment]
@morganmsrn you could ay least pass the `--ansi` flag for now or in the case of things like Pest there are different flags such as `--colors=always`.

To get it to work without these flags I can see Aaron has passed `FORCE_COLOR` into the environment but I am guessing there are a few more complexities with how Prompts and the underlying Symfony console output class are determining this under the hood compared to a normal terminal window.

**Comment by morganmsrn** [comment]
Using the `--ansi` flag directly in the Artisan commands defined in the provider fixed this issue, thank you.
