### ISSUE TITLE
Can't exit when running pail

### ISSUE THREAD

**Issue by donferi** [aarondfrancis/solo#27]
I'm trying to use [pail](https://github.com/laravel/pail) as a logs tab. It works and I can use the arrow keys to move between tabs etc. However when I try to quit via `q` or `ctrl+c` everything hangs and I can't quit or switch tabs anymore.

I can reproduce this even if I use `q` or `ctrl+c` in a different tab than the one running pail.

Things I've tried:
- running pail with `--no-interaction`
- with and without tmux
- native terminal and Alacritty (was desperate lol)

As soon as I remove pail from the commands, everything works as expected.

**Comment by aarondfrancis** [comment]
Gah, freakin pail! I think I fixed it. Lemme cut a new release
