### ISSUE TITLE
Compatibility with Sail commands

### ISSUE THREAD

**Issue by MarcEspiard** [aarondfrancis/solo#29]
Hey,

It's all in the title!

Great package, would love to be able to use it with sail commands that require to be running within docker, like schedule:work, queue:listen etc..

Still using it for Logs (pail) / Vite in the meantime :)

**Comment by aarondfrancis** [comment]
I'm going to need some more details! What happens if you run sail artisan queue:work outside of Solo and what happens when you run it as a Solo command?

**Comment by MarcEspiard** [comment]
Currently nothing happens :)
Running `php artisan solo`
with this config:
<img width="640" alt="image" src="https://github.com/user-attachments/assets/8e8f3a70-82dd-43f4-bc95-d91b024a5c1e">


The schedule command shows as Stopped and no output is shown:
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/44731105-641e-40ce-9fe0-dd9dd4ca5d8c">

Running the same  schedule command just in the terminal shows the usual schedule:work output:
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/98c70610-7075-4595-9442-a6a5b4b853f0">

Running `sail artisan solo` (so it runs within docker) and updating the schedule command to `php artisan schedule:work` (at this point we're inside the docker container so we need to call php as opposed to sail) works, but now the vite command won't work because npm does not exist inside the docker container (you can't run any command against your machine, you're inside the container since solo runs in it).

Ideally we would always run `php artisan solo` so we stay on the host machine, outside docker, and figure out how to make Sail commands work with solo, so we get the best of both worlds.

Sail uses docker compose exec, that same command translates to running `docker compose exec -u sail laravel.test php artisan schedule:work`

Hope this helps, let me know if you need more info.

**Comment by jesse-s** [comment]
`vendor/bin/sail artisan schedule:work --ansi` works

**Comment by aarondfrancis** [comment]
Ah ok, perfect! Thank you

**Comment by MarcEspiard** [comment]
Thanks for that, I should have tried that :)

Note, the process most likely returned an error like "command not found",
it would be a good improvement to display the error in solo, so users can
self help.

Cheers for looking into this to both.

**Comment by aarondfrancis** [comment]
Good thinking! I'll see what I can do there.

**Comment by joshmanders** [comment]
Outside of displaying the error to know whats going on, the reason this happens is because `vendor/bin` is not in the `$PATH`. This can be remedied (without users needing to add it to path) by adding it into the environment when Solo starts the process.

This is similarly how npm handles it when you run use a binary installed as a dependency.

**Comment by aarondfrancis** [comment]
Oh huh, I would've just assumed that it inherited the path that existed. Is that not true?

**Comment by joshmanders** [comment]
It probably inherits `$PATH` of the environment running the command, but most people don't have `./vendor/bin` in their PATH because it's a local directory, not a global directory.

**Comment by MarcEspiard** [comment]
> It probably inherits `$PATH` of the environment running the command, but most people don't have `./vendor/bin` in their PATH because it's a local directory, not a global directory.

That's correct, I expect most people to have it as an alias, it's suggested in the Sail docs during the install steps: https://laravel.com/docs/11.x/sail#configuring-a-shell-alias
It is how it's setup on my machines.

**Comment by joshmanders** [comment]
> > It probably inherits `$PATH` of the environment running the command, but most people don't have `./vendor/bin` in their PATH because it's a local directory, not a global directory.
> 
> That's correct, I expect most people to have it as an alias, it's suggested in the Sail docs during the install steps: https://laravel.com/docs/11.x/sail#configuring-a-shell-alias It is how it's setup on my machines.

Yup, so it may be beneficial to Solo to add `./vendor/bin` into the `$PATH` env for each command so that way you can just do `sail ...` inside your command script.

Maybe even add `./node_modules/.bin` too so you can quickly utilize npm binaries from your dependencies there too, such as `tailwindcss`
