### ISSUE TITLE
Running command in a directory other than /

### ISSUE THREAD

**Issue by kmizzi** [aarondfrancis/solo#36]
This doesn't seem to work

For example, my frontend is in Vue in  a frontend folder relative to base

I've tried:
'Frontend' => base_path("frontend") . '/yarn run serve',
'Frontend' => 'frontend/yarn run serve',
'Frontend' => 'cd frontend && yarn run serve',

Any other suggestions?

**Comment by aarondfrancis** [comment]
> This doesn't seem to work
Can you give me any more details?

In the directory where you run `php artisan solo`, what do you need to run to get `yarn run serve` to work? That will be the command you need to pass to Solo.

My guess is something like this: https://stackoverflow.com/questions/46891622/run-yarn-in-a-different-path

**Comment by kmizzi** [comment]
I apologize for the delay as github updates go into my "Optional" folder due to the unsubscribe keyword

This works!  yarn --cwd frontend/ run serve

I notice when rendering frontend there are no live updates?  Is there a toggle to enable this somewhere?

![image](https://github.com/user-attachments/assets/c549fb63-2eeb-4d0b-8ba8-da89ff2f6a2d)

**Comment by aarondfrancis** [comment]
Ah yeah, that'll likely have to wait until I finish a massive PR #4. 

If you don't want to wait, you might check to see if there is an option for vue-clie-service to disable the alt screen or output more simple progress.

**Comment by kmizzi** [comment]
Sounds good... ill wait for that PR!
